import CONFIG from './original-config'

CONFIG.PROXIO_WELCOME_TEXT = '瘋速修｜快速．專業．可靠'

CONFIG.PROXIO_HERO_TITLE_1 = '手機壞了？我們幫你搞定！'
CONFIG.PROXIO_HERO_TITLE_2 = '現場透明報價｜當日完修｜不留機'
CONFIG.PROXIO_HERO_BUTTON_1_TEXT = 'LINE 線上預約'
CONFIG.PROXIO_HERO_BUTTON_1_URL = 'https://lin.ee/DcZXmZ9'
CONFIG.PROXIO_HERO_BUTTON_2_TEXT = ''
CONFIG.PROXIO_HERO_BUTTON_2_URL = ''
CONFIG.PROXIO_HERO_BUTTON_2_ICON = ''

CONFIG.PROXIO_FEATURE_TITLE = '為什麼選擇瘋速修'
CONFIG.PROXIO_FEATURE_TEXT_1 = '我們修的不只是手機，更是您的日常'
CONFIG.PROXIO_FEATURE_TEXT_2 = '免費檢測｜晶片級維修｜30 分鐘完修'

CONFIG.PROXIO_FEATURE_1_TITLE_1 = '免費檢測'
CONFIG.PROXIO_FEATURE_1_TEXT_1 = '所有手機皆提供免費故障檢測，檢測後再報價，不強迫消費'
CONFIG.PROXIO_FEATURE_2_TITLE_1 = '晶片級維修'
CONFIG.PROXIO_FEATURE_2_TEXT_1 = '主機板、無訊號、進水等高階疑難雜症也能搞定'
CONFIG.PROXIO_FEATURE_3_TITLE_1 = '當日完修'
CONFIG.PROXIO_FEATURE_3_TEXT_1 = '現場報價，30 分鐘完修，不需留機，節省您的時間'

CONFIG.PROXIO_FEATURE_BUTTON_TEXT = '查看更多服務'
CONFIG.PROXIO_FEATURE_BUTTON_URL = '/services'

CONFIG.PROXIO_CTA_ENABLE = true
CONFIG.PROXIO_CTA_TITLE = '手機有狀況？'
CONFIG.PROXIO_CTA_TITLE_2 = '立即加入 LINE 預約瘋速修'
CONFIG.PROXIO_CTA_DESCRIPTION = '加入官方 LINE 預約快速維修，我們用專業守護您的連線品質'
CONFIG.PROXIO_CTA_BUTTON = true
CONFIG.PROXIO_CTA_BUTTON_URL = 'https://lin.ee/DcZXmZ9'
CONFIG.PROXIO_CTA_BUTTON_TEXT = '立即預約'

CONFIG.PROXIO_ABOUT_TITLE = '關於瘋速修'
CONFIG.PROXIO_ABOUT_TEXT_1 = '高雄手機維修專門品牌'
CONFIG.PROXIO_ABOUT_TEXT_2 = '我們在草衙、小港、鳳山設有門市，提供 iPhone 及 Android 現場快速維修、Apple IRP 授權原廠服務、主機板晶片級維修、透明報價與專業保固，讓維修過程不再繁瑣。'
CONFIG.PROXIO_ABOUT_PHOTO_URL = '/images/store.jpg'
CONFIG.PROXIO_ABOUT_KEY_1 = '門市數量'
CONFIG.PROXIO_ABOUT_VAL_1 = '3 間'
CONFIG.PROXIO_ABOUT_KEY_2 = '平均完修時間'
CONFIG.PROXIO_ABOUT_VAL_2 = '30 分鐘'
CONFIG.PROXIO_ABOUT_KEY_3 = '累積服務人數'
CONFIG.PROXIO_ABOUT_VAL_3 = '10,000+'
CONFIG.PROXIO_ABOUT_KEY_4 = 'Google 評價'
CONFIG.PROXIO_ABOUT_VAL_4 = '4.9★'
CONFIG.PROXIO_ABOUT_BUTTON_URL = '/locations'
CONFIG.PROXIO_ABOUT_BUTTON_TEXT = '查看門市資訊'

CONFIG.PROXIO_TESTIMONIALS_TITLE = '顧客好評回饋'
CONFIG.PROXIO_TESTIMONIALS_TEXT_1 = '你們的滿意，是我們最大的動力'
CONFIG.PROXIO_TESTIMONIALS_TEXT_2 = '真實客戶回饋，見證專業與誠信'
CONFIG.PROXIO_TESTIMONIALS_BUTTON_TEXT = '更多評價'
CONFIG.PROXIO_TESTIMONIALS_BUTTON_URL = '/reviews'
CONFIG.PROXIO_TESTIMONIALS_ITEMS = [
  {
    PROXIO_TESTIMONIALS_ITEM_TEXT: '螢幕壞掉立刻來，30分鐘就修好，速度快又專業，非常推薦！',
    PROXIO_TESTIMONIALS_ITEM_AVATAR: '/avatar1.png',
    PROXIO_TESTIMONIALS_ITEM_NICKNAME: '小港阿宏',
    PROXIO_TESTIMONIALS_ITEM_DESCRIPTION: '在地顧客',
    PROXIO_TESTIMONIALS_ITEM_URL: '#'
  },
  {
    PROXIO_TESTIMONIALS_ITEM_TEXT: 'LINE預約超方便，還有終生保固，超有誠意！',
    PROXIO_TESTIMONIALS_ITEM_AVATAR: '/avatar2.png',
    PROXIO_TESTIMONIALS_ITEM_NICKNAME: '陳小姐',
    PROXIO_TESTIMONIALS_ITEM_DESCRIPTION: 'iPhone 11 使用者',
    PROXIO_TESTIMONIALS_ITEM_URL: '#'
  },
  {
    PROXIO_TESTIMONIALS_ITEM_TEXT: '之前別家說主機板壞要留機，來這裡直接當場修好，技術真的強！',
    PROXIO_TESTIMONIALS_ITEM_AVATAR: '/avatar3.png',
    PROXIO_TESTIMONIALS_ITEM_NICKNAME: '阿哲',
    PROXIO_TESTIMONIALS_ITEM_DESCRIPTION: '安卓用戶',
    PROXIO_TESTIMONIALS_ITEM_URL: '#'
  }
]

export default CONFIG
